-- Migration 017 — Allow 'rampwin' as an OTP delivery channel
--
-- Rampwin is a WhatsApp Business API gateway (a third-party BSP).
-- Semantically the patient receives a WhatsApp message either way, but
-- we keep the provider distinct in otp_verifications.channel so logs
-- and analytics can tell Meta-direct ('whatsapp') from Rampwin-routed
-- ('rampwin') deliveries.
--
-- Migration 011 created the original CHECK with only ('whatsapp', 'sms');
-- this migration drops it by-name (discovered defensively in case the
-- autogenerated name differs in production) and re-creates it with the
-- expanded set.
--
-- Idempotent: safe to re-run.

DO $$
DECLARE
  v_constraint text;
BEGIN
  -- Find whatever CHECK constraint on otp_verifications references the
  -- `channel` column. Postgres normally names inline checks
  -- '<table>_<column>_check' but that's not guaranteed across all
  -- environments, so we look it up by structure instead of by name.
  SELECT conname
    INTO v_constraint
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public'
    AND t.relname = 'otp_verifications'
    AND c.contype = 'c'
    AND pg_get_constraintdef(c.oid) ILIKE '%channel%IN%'
  LIMIT 1;

  IF v_constraint IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.otp_verifications DROP CONSTRAINT %I',
      v_constraint
    );
  END IF;
END $$;

ALTER TABLE public.otp_verifications
  ADD CONSTRAINT otp_verifications_channel_check
  CHECK (channel IN ('whatsapp', 'sms', 'rampwin'));

COMMENT ON CONSTRAINT otp_verifications_channel_check
  ON public.otp_verifications IS
  'Which delivery provider sent the OTP. ''whatsapp'' = Meta Cloud API direct, ''rampwin'' = WhatsApp via the Rampwin BSP, ''sms'' = MSG91. Expanded in M017 to add ''rampwin''.';
